#ifndef __YYError_H
#define __YYError_H

class YYError 
{
public:
	enum 
	{
		_RES_SUCCESS = 200,
		RES_FAILED = 1,

		_NO_ERROR = 0,

		CODE_NETWORK_UNAVAILABLE = 1,
		CODE_NETWORK_FAILED = 2,
		CODE_LINKD_DISCONNECTED = 3,
		CODE_LINKD_CONNECTED = 4,
		CODE_LINKD_CONNECTING = 5,
		CODE_PINCODE_ERROR = 6,
		CODE_LOGIN_FAILED = 7,

		INVALID_ARG = 8,
		INVALID_STATE = 9,
		CONNECT_FAIL = 10,
		E_NETWORK = 11,
		UNKNOWN = 12,
		TIMEOUT = 13,
		NULL_DATA = 14,
		INVALID_DATA = 15,
		SERVER_REJECT = 16,
		IM_KICK = 17,
		GLOBAL_KICK = 18,
		CANCELLED = 19,
		E_INTERNAL = 20,
		INVALID_APPSECRET = 21,
		INVALID_COOKIE = 22,
		USER_AUTH_FAIL = 23,
		APP_BLACKLIST = 24,
		USER_BLACKLIST = 25,
		E_NETWORK_LBS = 26, // lbs连接失败

		RES_VERSION_TOO_LOW = 505, //后台不支持此版本协议
		RES_PIN_WRONG = 521,
		RES_PIN_EXISTS = 522,
		RES_PIN_NOEXIST = 524, //手机号不存在或者pin code 已经过期
		RES_PIN_SEND_ERROR = 525, //短信发送失败
		RES_USER_NO_PASSWORD = 533, //用户未设密码	
		RES_ETOGROUPLIMIT = 788,//群组人数超过上限

		CALL_NO_ERR = 0,
		CALL_ERR_UNKNOWN = -1,
		CALL_ERR_LINKD_DISCONNECTED = -2,
		CALL_ERR_SESSION_STATE = -3,
	};
};

#endif //__YYError_H